# Copyright 2026 The Kube SRE MCP Authors
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
        update-types:
          - minor
          - patch
      prometheus:
        patterns:
          - "github.com/prometheus/*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
