# Copyright 2026 The Kube SRE MCP Authors
# SPDX-License-Identifier: Apache-2.0
name: License

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: license-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license:
    name: license
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Apache-2.0 and SPDX checks
        run: make license-check
